Repository niamtokik/cozo, pull requests merged in 2023-09, with the labels that each got.

#15 add cozo nif lib as github artifact
  .github/workflows/test.yaml
Labels: enhancement

#24 Update notes (#21)
  Makefile
  README.md
  notes/0001-integrating-cozodb-in-erlang-ecosystem/README.md
  src/cozo.app.src
  src/cozo.erl
  test/cozo_SUITE.erl
Labels: documentation, enhancement

#23 Add support for cozodb 0.7.5
  Makefile
  README.md
Labels: enhancement

#25 Update README.md
  README.md
Labels: bug, enhancement

#28 Removed a rebar.config entry that is not required and added some example apps in erlang and elixir
  examples/elixir_app/.formatter.exs
  examples/elixir_app/.gitignore
  examples/elixir_app/README.md
  examples/elixir_app/lib/elixir_app.ex
  examples/elixir_app/mix.exs
  examples/elixir_app/mix.lock
  examples/elixir_app/test/elixir_app_test.exs
  examples/elixir_app/test/test_helper.exs
  examples/erlang_app/.gitignore
  examples/erlang_app/LICENSE.md
  examples/erlang_app/README.md
  examples/erlang_app/rebar.config
  examples/erlang_app/rebar.lock
  examples/erlang_app/src/erlang_app.app.src
  examples/erlang_app/src/erlang_app_app.erl
  examples/erlang_app/src/erlang_app_sup.erl
  rebar.config
Labels: documentation, enhancement
